# Site settings
title: NeptLiang
email: neptliang@outlook.com
description: "MING has traveled here"
baseurl: ""
url: "http://neptliang.github.io"
twitter_username: NeptLiang
github_username:  NEPTLIANG

# Build settings
markdown: kramdown
permalink: pretty
